[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    source ~/.dotfiles/.vim/rc/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme='iceberg'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
