[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    source ~/.dotfiles/.vim/rc/plugins/color.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
merged = 0
depends = ['vim-airline-themes']
hook_add = '''
    source ~/.vim/rc/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes
    let g:gitgutter_async = 1
    let g:gitgutter_sign_modified = 'rw'
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=yellow
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=yellow
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
#marged = 0
hook_add = '''
    source ~/.vim/rc/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
    source ~/.vim/rc/plugins/snippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''

'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
source ~/.vim/rc/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
#hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    set rtp+=/opt/homebrew/opt/fzf
    command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
    \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \ <bang>0)
    "nnoremap <C-g> :Rg<Space>
    "nnoremap <C-p> :GFiles<CR>
    "nnoremap <C-h> :History<CR>
'''

